# Event
credits_reached = "The End of Everything"

filler = "A Filler item"
mirror = "The Mirror"
gift = "A Gift"

# Dagger
dagger = "Pristine Dagger"
dagger1 = "Pristine Dagger - Chapter 1"
dagger2 = "Pristine Dagger - Chapter 2"
dagger3 = "Pristine Dagger - Chapter 3"

dagger_princess = "Pristine Dagger - The Princess"
dagger_adversary = "Pristine Dagger - The Adversary"
dagger_tower = "Pristine Dagger - The Tower"
dagger_spectre = "Pristine Dagger - The Spectre"
dagger_nightmare = "Pristine Dagger - The Nightmare"
dagger_razor = "Pristine Dagger - The Razor"
dagger_beast = "Pristine Dagger - The Beast"
dagger_witch = "Pristine Dagger - The Witch"
dagger_stranger = "Pristine Dagger - The Stranger"
dagger_prisoner = "Pristine Dagger - The Prisoner"
dagger_damsel = "Pristine Dagger - The Damsel"
dagger_needle = "Pristine Dagger - The Eye of the Needle"
dagger_fury = "Pristine Dagger - The Fury"
dagger_apotheosis = "Pristine Dagger - The Apotheosis"
dagger_dragon = "Pristine Dagger - The Princess and the Dragon"
dagger_den = "Pristine Dagger - The Den"
dagger_wild = "Pristine Dagger - The Wild"
dagger_thorn = "Pristine Dagger - The Thorn"
dagger_cage = "Pristine Dagger - The Cage"
dagger_grey = "Pristine Dagger - The Grey"
dagger_happily = "Pristine Dagger - The Happily Ever After"
dagger_goddess = "Pristine Dagger - The End of Everything"

# Princesses
adversary = "The Adversary (Princess)"
tower = "The Tower (Princess)"
spectre = "The Spectre (Princess)"
nightmare = "The Nightmare (Princess)"
razor = "The Razor (Princess)"
beast = "The Beast (Princess)"
witch = "The Witch (Princess)"
stranger = "The Stranger (Princess)"
prisoner = "The Prisoner (Princess)"
damsel = "The Damsel (Princess)"

needle = "The Eye of the Needle (Princess)"
fury = "The Fury (Princess)"
apotheosis = "The Apotheosis (Princess)"
dragon = "The Princess and the Dragon (Princess)"
wraith = "The Wraith (Princess)"
clarity = "The Moment of Clarity (Princess)"
den = "The Den (Princess)"
wild = "The Wild (Princess)"
thorn = "The Thorn (Princess)"
cage = "The Cage (Princess)"
grey = "The Grey (Princess)"
happily = "Happily Ever After (Princess)"

goddess = "The Shifting Mound (Princess)"

# Voices
stubborn = "The Stubborn (Voice)"
broken = "The Broken (Voice)"
cold = "The Cold (Voice)"
paranoid = "The Paranoid (Voice)"
cheated = "The Cheated (Voice)"
hunted = "The Hunted (Voice)"
opportunist = "The Opportunist (Voice)"
contrarian = "The Contrarian (Voice)"
skeptic = "The Skeptic (Voice)"
smitten = "The Smitten (Voice)"
