win = "Victory Condition"

# Chapter
chap2 = "Reach Chapter 2"
chap3 = "Reach Chapter 3"

# The Long Quiet
mirror1 = "The Body"
mirror2 = "The Bloat"
mirror3 = "The Decay"
mirror4 = "The Remains"
mirror5 = "The Long Quiet"

# Princesses
adversary = "Find The Adversary"
tower = "Find The Tower"
spectre = "Find The Spectre"
nightmare = "Find The Nightmare"
razor = "Find The Razor"
beast = "Find The Beast"
witch = "Find The Witch"
stranger = "Find The Stranger"
prisoner = "Find The Prisoner"
damsel = "Find The Damsel"

needle = "Find The Eye of the Needle"
fury = "Find The Fury"
apotheosis = "Find The Apotheosis"
dragon = "Find The Princess and the Dragon"
wraith = "Find The Wraith"
clarity = "Find The Moment of Clarity"
den = "Find Den"
wild = "Find The Wild"
thorn = "Find The Thorn"
cage = "Find The Cage"
grey = "Find The Grey"
happily = "Find Happily Ever After"

goddess = "Find The Shifting Mound"

# Heart
adversary_heart = "A Bold Heart"
tower_heart = "An Overwhelming Heart"
spectre_heart = "A Yearning Heart"
nightmare_heart = "A Tender Heart"
razor_heart_iron = "A Piercing Heart in a Cage of Iron"
razor_heart_free = "A Piercing Heart, Beating Free"
beast_heart = "A Cunning Heart"
witch_heart = "A Righteous Heart"
stranger_heart = "A Rich and Vibrant Heart"
prisoner_heart_patient = "A Patient Heart"
prisoner_heart_clever = "A Clever Heart"
damsel_heart_gentle = "A Gentle Heart"
damsel_heart_pliable = "A Pliable Heart"

needle_heart = "A Burning Heart"
fury_heart_weathered = "A Weathered Heart"
fury_heart_unwound = "An Unwound and Weathered Heart"
apotheosis_heart = "A Terrifying and Divine Heart"
dragon_heart_main = "An Empathetic Heart"
dragon_heart_stencil = "An Empathetic Heart, Held in Stencil"
wraith_heart = "A Driven Heart"
clarity_heart = "A Wise Heart"
den_heart = "A Ravenous Heart"
wild_heart_curious = "A Curious and Beautiful Heart"
wild_heart_scarred = "A Scarred and Beautiful Heart"
thorn_heart = "A Cautious Heart"
cage_heart_open = "An Open Heart, or a Watchful One"
grey_heart_bright = "A Bright Heart"
grey_heart_deep = "A Deep Heart"
happily_heart = "An Honest Heart"
