import Region
from TrackerSystem import max_reachable_vessels, can_reach_oblivion, can_reach_new_world

def _gallery_list(route_name, count) -> list[str]:
    # Index 0 is intentionally empty so callers can use 1-based gallery indexes.
    return [""] + [f"Gallery - {route_name} [{i}]" for i in range(1, count + 1)]

# Beginnings & Endings
princess: list[str] = _gallery_list("The Hero and the Princess", 18)
spaceBetween: list[str] = _gallery_list("The Spaces Between", 9)
finale: list[str] = _gallery_list("The End of Everything", 20)

# 1st Row
adversary: list[str] = _gallery_list("The Adversary", 20)
tower: list[str] = _gallery_list("The Tower", 13)
spectre: list[str] = _gallery_list("The Spectre", 18)
nightmare: list[str] = _gallery_list("The Nightmare", 19)
razor: list[str] = _gallery_list("The Razor", 20)
beast: list[str] = _gallery_list("The Beast", 17)
witch: list[str] = _gallery_list("The Witch", 20)
stranger: list[str] = _gallery_list("The Stranger", 12)
prisoner: list[str] = _gallery_list("The Prisoner", 17)
damsel: list[str] = _gallery_list("The Damsel", 20)

# 2nd Row
needle: list[str] = _gallery_list("The Eye of the Needle", 20)
fury: list[str] = _gallery_list("The Fury", 20)
apotheosis: list[str] = _gallery_list("The Apotheosis", 20)
dragon: list[str] = _gallery_list("The Princess and the Dragon", 20)
wraith: list[str] = _gallery_list("The Wraith", 11)
clarity: list[str] = _gallery_list("The Moment of Clarity", 14)
den: list[str] = _gallery_list("The Den", 20)
wild: list[str] = _gallery_list("The Wild", 12)
thorn: list[str] = _gallery_list("The Thorn", 19)
cage: list[str] = _gallery_list("The Cage", 20)
grey: list[str] = _gallery_list("The Grey", 20)
happily: list[str] = _gallery_list("Happily Ever After", 20)

GALLERY_REQUIREMENTS = {
    princess[1]: [Region.one, None],
    princess[2]: [Region.one, None],
    princess[3]: [Region.one, None],
    princess[4]: [Region.one, None],
    princess[5]: [Region.tower, None],
    princess[6]: [Region.damsel, None],
    princess[7]: [Region.nightmare, None],
    princess[8]: [Region.prisoner, None],
    princess[9]: [Region.spectre, None],
    princess[10]: [Region.razor, None],
    princess[11]: [Region.witch, None],
    princess[12]: [Region.beast, None],
    princess[13]: [Region.adversary, None],
    princess[14]: [Region.stranger, None],
    princess[15]: [Region.one_blade, None],
    princess[16]: [Region.one_blade, None],
    princess[17]: [Region.one_blade, None],
    princess[18]: [Region.one_blade, None],

    spaceBetween[1]: [Region.space_between, max_reachable_vessels, 1],
    spaceBetween[2]: [Region.space_between, max_reachable_vessels, 1],
    spaceBetween[3]: [Region.space_between, max_reachable_vessels, 1],
    spaceBetween[4]: [Region.space_between, max_reachable_vessels, 2],
    spaceBetween[5]: [Region.space_between, max_reachable_vessels, 3],
    spaceBetween[6]: [Region.space_between, max_reachable_vessels, 4],
    spaceBetween[7]: [Region.space_between, max_reachable_vessels, 5, False],
    spaceBetween[8]: [Region.goddess, max_reachable_vessels, 5],
    spaceBetween[9]: [Region.oblivion, can_reach_oblivion, 6],

    finale[1]: [Region.goddess, max_reachable_vessels, 5],
    finale[2]: [Region.goddess, max_reachable_vessels, 5],
    finale[3]: [Region.goddess, max_reachable_vessels, 5],
    finale[4]: [Region.goddess, max_reachable_vessels, 5],
    finale[5]: [Region.goddess, max_reachable_vessels, 5],
    finale[6]: [Region.goddess, max_reachable_vessels, 5],
    finale[7]: [Region.goddess_blade, max_reachable_vessels, 5],
    finale[8]: [Region.goddess_blade, max_reachable_vessels, 5],
    finale[9]: [Region.goddess, max_reachable_vessels, 5],
    finale[10]: [Region.goddess, max_reachable_vessels, 5],
    finale[11]: [Region.stranger_blade, max_reachable_vessels, 5],
    finale[12]: [Region.stranger_goddess_blade, max_reachable_vessels, 5],
    finale[13]: [Region.stranger_blade, max_reachable_vessels, 5],
    finale[14]: [Region.stranger_goddess_blade, max_reachable_vessels, 5],
    finale[15]: [Region.goddess_blade, max_reachable_vessels, 5],
    finale[16]: [Region.new_world, can_reach_new_world],
    finale[17]: [Region.new_world, can_reach_new_world],
    finale[18]: [Region.new_world, can_reach_new_world],
    finale[19]: [Region.new_world, can_reach_new_world],
    finale[20]: [Region.new_world, can_reach_new_world],

    adversary[1]: [Region.adversary, None],
    adversary[2]: [Region.adversary, None],
    adversary[3]: [Region.adversary_blade, None],
    adversary[4]: [Region.adversary, None],
    adversary[5]: [Region.adversary_blade, None],
    adversary[6]: [Region.adversary, None],
    adversary[7]: [Region.adversary_blade, None],
    adversary[8]: [Region.adversary_blade, None],
    adversary[9]: [Region.adversary_blade, None],
    adversary[10]: [Region.adversary_blade, None],
    adversary[11]: [Region.adversary, None],
    adversary[12]: [Region.adversary, None],
    adversary[13]: [Region.adversary, None],
    adversary[14]: [Region.adversary_blade, None],
    adversary[15]: [Region.adversary_blade, None],
    adversary[16]: [Region.adversary_blade, None],
    adversary[17]: [Region.adversary_blade, None],
    adversary[18]: [Region.adversary_blade, max_reachable_vessels, 1],
    adversary[19]: [Region.adversary_blade, max_reachable_vessels, 1],
    adversary[20]: [Region.adversary_blade, max_reachable_vessels, 5],

    tower[1]: [Region.tower, None],
    tower[2]: [Region.tower, None],
    tower[3]: [Region.tower_blade, None],
    tower[4]: [Region.tower_blade, None],
    tower[5]: [Region.tower, None],
    tower[6]: [Region.tower, None],
    tower[7]: [Region.tower, None],
    tower[8]: [Region.tower_blade, None],
    tower[9]: [Region.tower_blade, None],
    tower[10]: [Region.tower_blade, None],
    tower[11]: [Region.tower, max_reachable_vessels, 1],
    tower[12]: [Region.tower, max_reachable_vessels, 1],
    tower[13]: [Region.tower, max_reachable_vessels, 5],

    spectre[1]: [Region.spectre, None],
    spectre[2]: [Region.spectre, None],
    spectre[3]: [Region.spectre, None],
    spectre[4]: [Region.spectre, None],
    spectre[5]: [Region.spectre, None],
    spectre[6]: [Region.spectre, None],
    spectre[7]: [Region.spectre, None],
    spectre[8]: [Region.spectre, None],
    spectre[9]: [Region.spectre, None],
    spectre[10]: [Region.spectre, None],
    spectre[11]: [Region.spectre_blade, None],
    spectre[12]: [Region.spectre_blade, None],
    spectre[13]: [Region.spectre, None],
    spectre[14]: [Region.spectre_blade, None],
    spectre[15]: [Region.spectre, None],
    spectre[16]: [Region.spectre, max_reachable_vessels, 1],
    spectre[17]: [Region.spectre, max_reachable_vessels, 1],
    spectre[18]: [Region.spectre, max_reachable_vessels, 5],

    nightmare[1]: [Region.nightmare, None],
    nightmare[2]: [Region.nightmare, None],
    nightmare[3]: [Region.nightmare, None],
    nightmare[4]: [Region.nightmare, None],
    nightmare[5]: [Region.nightmare, None],
    nightmare[6]: [Region.nightmare, None],
    nightmare[7]: [Region.nightmare, None],
    nightmare[8]: [Region.nightmare_blade, None],
    nightmare[9]: [Region.nightmare_blade, None],
    nightmare[10]: [Region.nightmare_blade, None],
    nightmare[11]: [Region.nightmare, None],
    nightmare[12]: [Region.nightmare, None],
    nightmare[13]: [Region.nightmare, None],
    nightmare[14]: [Region.nightmare, None],
    nightmare[15]: [Region.nightmare, None],
    nightmare[16]: [Region.nightmare, None],
    nightmare[17]: [Region.nightmare, max_reachable_vessels, 1],
    nightmare[18]: [Region.nightmare, max_reachable_vessels, 1],
    nightmare[19]: [Region.nightmare, max_reachable_vessels, 5],

    razor[1]: [Region.razor, None],
    razor[2]: [Region.razor, None],
    razor[3]: [Region.razor_blade, None],
    razor[4]: [Region.razor, None],
    razor[5]: [Region.razor, None],
    razor[6]: [Region.razor_chap3, None],
    razor[7]: [Region.razor_chap3, None],
    razor[8]: [Region.razor_chap3, None],
    razor[9]: [Region.razor_no_way, None],
    razor[10]: [Region.razor_chap3, None],
    razor[11]: [Region.razor_chap3, None],
    razor[12]: [Region.razor_chap4, None],
    razor[13]: [Region.razor_destruction, None],
    razor[14]: [Region.razor_empty, None],
    razor[15]: [Region.razor_empty, None],
    razor[16]: [Region.razor_destruction, max_reachable_vessels, 1],
    razor[17]: [Region.razor_destruction, max_reachable_vessels, 1],
    razor[18]: [Region.razor_empty, max_reachable_vessels, 1],
    razor[19]: [Region.razor_empty, max_reachable_vessels, 1],
    razor[20]: [Region.razor_chap4, max_reachable_vessels, 5],

    beast[1]: [Region.beast, None],
    beast[2]: [Region.beast, None],
    beast[3]: [Region.beast, None],
    beast[4]: [Region.beast_blade, None],
    beast[5]: [Region.beast, None],
    beast[6]: [Region.beast_blade, None],
    beast[7]: [Region.beast_blade, None],
    beast[8]: [Region.beast_blade, None],
    beast[9]: [Region.beast, None],
    beast[10]: [Region.beast, None],
    beast[11]: [Region.beast, None],
    beast[12]: [Region.beast, None],
    beast[13]: [Region.beast_blade, None],
    beast[14]: [Region.beast, None],
    beast[15]: [Region.beast, max_reachable_vessels, 1],
    beast[16]: [Region.beast, max_reachable_vessels, 1],
    beast[17]: [Region.beast, max_reachable_vessels, 5],

    witch[1]: [Region.witch, None],
    witch[2]: [Region.witch, None],
    witch[3]: [Region.witch_blade, None],
    witch[4]: [Region.witch_blade, None],
    witch[5]: [Region.witch_blade, None],
    witch[6]: [Region.witch_blade, None],
    witch[7]: [Region.witch_blade, None],
    witch[8]: [Region.witch_blade, None],
    witch[9]: [Region.witch_blade, None],
    witch[10]: [Region.witch, None],
    witch[11]: [Region.witch_blade, None],
    witch[12]: [Region.witch, None],
    witch[13]: [Region.witch, None],
    witch[14]: [Region.witch, None],
    witch[15]: [Region.witch, None],
    witch[16]: [Region.witch_blade, None],
    witch[17]: [Region.witch, max_reachable_vessels, 1],
    witch[18]: [Region.witch, max_reachable_vessels, 1],
    witch[19]: [Region.witch, max_reachable_vessels, 5],
    witch[20]: [Region.witch, max_reachable_vessels, 5],

    stranger[1]: [Region.stranger, None],
    stranger[2]: [Region.stranger, None],
    stranger[3]: [Region.stranger, None],
    stranger[4]: [Region.stranger, None],
    stranger[5]: [Region.stranger, None],
    stranger[6]: [Region.stranger_blade, None],
    stranger[7]: [Region.stranger_blade, None],
    stranger[8]: [Region.stranger_blade, None],
    stranger[9]: [Region.stranger_blade, None],
    stranger[10]: [Region.stranger_blade, max_reachable_vessels, 1],
    stranger[11]: [Region.stranger_blade, max_reachable_vessels, 1],
    stranger[12]: [Region.stranger_blade, max_reachable_vessels, 5],

    prisoner[1]: [Region.prisoner, None],
    prisoner[2]: [Region.prisoner, None],
    prisoner[3]: [Region.prisoner, None],
    prisoner[4]: [Region.prisoner, None],
    prisoner[5]: [Region.prisoner, None],
    prisoner[6]: [Region.prisoner, None],
    prisoner[7]: [Region.prisoner, None],
    prisoner[8]: [Region.prisoner, None],
    prisoner[9]: [Region.prisoner_blade, None],
    prisoner[10]: [Region.prisoner_blade, None],
    prisoner[11]: [Region.prisoner_blade, None],
    prisoner[12]: [Region.prisoner, None],
    prisoner[13]: [Region.prisoner, max_reachable_vessels, 1],
    prisoner[14]: [Region.prisoner, max_reachable_vessels, 1],
    prisoner[15]: [Region.prisoner, max_reachable_vessels, 1],
    prisoner[16]: [Region.prisoner, max_reachable_vessels, 1],
    prisoner[17]: [Region.prisoner, max_reachable_vessels, 5],

    damsel[1]: [Region.damsel, None],
    damsel[2]: [Region.damsel, None],
    damsel[3]: [Region.damsel, None],
    damsel[4]: [Region.damsel, None],
    damsel[5]: [Region.damsel, None],
    damsel[6]: [Region.damsel, None],
    damsel[7]: [Region.damsel, None],
    damsel[8]: [Region.damsel, None],
    damsel[9]: [Region.damsel, None],
    damsel[10]: [Region.damsel, None],
    damsel[11]: [Region.damsel, None],
    damsel[12]: [Region.damsel_blade, None],
    damsel[13]: [Region.damsel_blade, None],
    damsel[14]: [Region.damsel_blade, None],
    damsel[15]: [Region.damsel_blade, None],
    damsel[16]: [Region.damsel, None],
    damsel[17]: [Region.damsel, max_reachable_vessels, 1],
    damsel[18]: [Region.damsel, max_reachable_vessels, 1],
    damsel[19]: [Region.damsel, max_reachable_vessels, 1],
    damsel[20]: [Region.damsel, max_reachable_vessels, 5],

    needle[1]: [Region.needle, None],
    needle[2]: [Region.needle, None],
    needle[3]: [Region.needle, None],
    needle[4]: [Region.needle, None],
    needle[5]: [Region.needle_blade, None],
    needle[6]: [Region.needle_blade, None],
    needle[7]: [Region.needle, None],
    needle[8]: [Region.needle, None],
    needle[9]: [Region.needle_hunted_blade, None],
    needle[10]: [Region.needle_hunted_blade, None],
    needle[11]: [Region.needle_hunted_blade, None],
    needle[12]: [Region.needle_hunted_blade, None],
    needle[13]: [Region.needle_hunted_blade, None],
    needle[14]: [Region.needle_skeptic, None],
    needle[15]: [Region.needle, None],
    needle[16]: [Region.needle, None],
    needle[17]: [Region.needle, None],
    needle[18]: [Region.needle, max_reachable_vessels, 1],
    needle[19]: [Region.needle, max_reachable_vessels, 1],
    needle[20]: [Region.needle, max_reachable_vessels, 5],

    fury[1]: [Region.fury, None],
    fury[2]: [Region.fury, None],
    fury[3]: [Region.fury, None],
    fury[4]: [Region.fury, None],
    fury[5]: [Region.fury_broken_cold_blade, None],
    fury[6]: [Region.fury_broken_cold, None],
    fury[7]: [Region.fury_broken_cold, None],
    fury[8]: [Region.fury_contrarian, None],
    fury[9]: [Region.fury_tower, None],
    fury[10]: [Region.fury_contrarian, None],
    fury[11]: [Region.fury_contrarian, None],
    fury[12]: [Region.fury_tower_blade, None],
    fury[13]: [Region.fury_tower_blade, None],
    fury[14]: [Region.fury_tower_blade, None],
    fury[15]: [Region.fury, None],
    fury[16]: [Region.fury, None],
    fury[17]: [Region.fury_broken_cold, None],
    fury[18]: [Region.fury_weathered_heart, max_reachable_vessels, 1],
    fury[19]: [Region.fury_unwound_heart, max_reachable_vessels, 1],
    fury[20]: [Region.fury, max_reachable_vessels, 5],

    apotheosis[1]: [Region.apotheosis, None],
    apotheosis[2]: [Region.apotheosis, None],
    apotheosis[3]: [Region.apotheosis_blade, None],
    apotheosis[4]: [Region.apotheosis_paranoid_blade, None],
    apotheosis[5]: [Region.apotheosis_paranoid_blade, None],
    apotheosis[6]: [Region.apotheosis_paranoid_sword, None],
    apotheosis[7]: [Region.apotheosis_paranoid_sword, None],
    apotheosis[8]: [Region.apotheosis, None],
    apotheosis[9]: [Region.apotheosis_contrarian_blade, None],
    apotheosis[10]: [Region.apotheosis_contrarian_blade, None],
    apotheosis[11]: [Region.apotheosis_contrarian_blade, None],
    apotheosis[12]: [Region.apotheosis, None],
    apotheosis[13]: [Region.apotheosis, None],
    apotheosis[14]: [Region.apotheosis, None],
    apotheosis[15]: [Region.apotheosis, None],
    apotheosis[16]: [Region.apotheosis, None],
    apotheosis[17]: [Region.apotheosis, None],
    apotheosis[18]: [Region.apotheosis, max_reachable_vessels, 1],
    apotheosis[19]: [Region.apotheosis, max_reachable_vessels, 1],
    apotheosis[20]: [Region.apotheosis, max_reachable_vessels, 5],

    dragon[1]: [Region.spectre_blade, None],
    dragon[2]: [Region.spectre_blade, None],
    dragon[3]: [Region.dragon, None],
    dragon[4]: [Region.dragon, None],
    dragon[5]: [Region.dragon, None],
    dragon[6]: [Region.dragon, None],
    dragon[7]: [Region.dragon_kind, None],
    dragon[8]: [Region.dragon, None],
    dragon[9]: [Region.dragon, None],
    dragon[10]: [Region.dragon_harsh, None],
    dragon[11]: [Region.dragon_harsh, None],
    dragon[12]: [Region.dragon_kind, None],
    dragon[13]: [Region.dragon_kind_blade, None],
    dragon[14]: [Region.dragon_harsh, None],
    dragon[15]: [Region.dragon_kind, None],
    dragon[16]: [Region.dragon, None],
    dragon[17]: [Region.dragon, max_reachable_vessels, 1],
    dragon[18]: [Region.dragon, max_reachable_vessels, 1],
    dragon[19]: [Region.dragon, max_reachable_vessels, 1],
    dragon[20]: [Region.dragon, max_reachable_vessels, 5],

    wraith[1]: [Region.wraith, None],
    wraith[2]: [Region.wraith, None],
    wraith[3]: [Region.wraith, None],
    wraith[4]: [Region.wraith, None],
    wraith[5]: [Region.wraith, None],
    wraith[6]: [Region.wraith, None],
    wraith[7]: [Region.wraith, None],
    wraith[8]: [Region.wraith, None],
    wraith[9]: [Region.wraith, max_reachable_vessels, 1],
    wraith[10]: [Region.wraith, max_reachable_vessels, 1],
    wraith[11]: [Region.wraith, max_reachable_vessels, 5],

    clarity[1]: [Region.clarity, None],
    clarity[2]: [Region.clarity, None],
    clarity[3]: [Region.clarity, None],
    clarity[4]: [Region.clarity_blade, None],
    clarity[5]: [Region.clarity_blade, None],
    clarity[6]: [Region.clarity_blade, None],
    clarity[7]: [Region.clarity_blade, None],
    clarity[8]: [Region.clarity_blade, None],
    clarity[9]: [Region.clarity_blade, None],
    clarity[10]: [Region.clarity_blade, None],
    clarity[11]: [Region.clarity_blade, None],
    clarity[12]: [Region.clarity_blade, max_reachable_vessels, 1],
    clarity[13]: [Region.clarity_blade, max_reachable_vessels, 1],
    clarity[14]: [Region.clarity_blade, max_reachable_vessels, 5],

    den[1]: [Region.den, None],
    den[2]: [Region.den, None],
    den[3]: [Region.den, None],
    den[4]: [Region.den_stubborn_blade, None],
    den[5]: [Region.den_stubborn_blade, None],
    den[6]: [Region.den_stubborn_blade, None],
    den[7]: [Region.den_stubborn_blade, None],
    den[8]: [Region.den_skeptic_blade, None],
    den[9]: [Region.den_skeptic, None],
    den[10]: [Region.den_skeptic, None],
    den[11]: [Region.den_skeptic, None],
    den[12]: [Region.den_skeptic, None],
    den[13]: [Region.den_skeptic, None],
    den[14]: [Region.den_skeptic, None],
    den[15]: [Region.den_skeptic, None],
    den[16]: [Region.den_stubborn_blade, None],
    den[17]: [Region.den_stubborn_blade, None],
    den[18]: [Region.den, max_reachable_vessels, 1],
    den[19]: [Region.den, max_reachable_vessels, 1],
    den[20]: [Region.den, max_reachable_vessels, 5],

    wild[1]: [Region.wild, None],
    wild[2]: [Region.wild, None],
    wild[3]: [Region.wild, None],
    wild[4]: [Region.wild_blade, None],
    wild[5]: [Region.wild_blade, None],
    wild[6]: [Region.wild_blade, None],
    wild[7]: [Region.wild, max_reachable_vessels, 1],
    wild[8]: [Region.wild, max_reachable_vessels, 1],
    wild[9]: [Region.wild_blade, max_reachable_vessels, 1],
    wild[10]: [Region.wild_blade, max_reachable_vessels, 1],
    wild[11]: [Region.wild, max_reachable_vessels, 5],
    wild[12]: [Region.wild_blade, max_reachable_vessels, 5],

    thorn[1]: [Region.thorn, None],
    thorn[2]: [Region.thorn, None],
    thorn[3]: [Region.thorn, None],
    thorn[4]: [Region.thorn, None],
    thorn[5]: [Region.thorn_blade, None],
    thorn[6]: [Region.thorn, None],
    thorn[7]: [Region.thorn, None],
    thorn[8]: [Region.thorn_blade, None],
    thorn[9]: [Region.thorn_blade, None],
    thorn[10]: [Region.thorn_blade, None],
    thorn[11]: [Region.thorn_blade, None],
    thorn[12]: [Region.thorn_blade, None],
    thorn[13]: [Region.thorn_blade, None],
    thorn[14]: [Region.thorn_blade, None],
    thorn[15]: [Region.thorn_smitten_blade, None],
    thorn[16]: [Region.thorn_smitten_blade, None],
    thorn[17]: [Region.thorn, max_reachable_vessels, 1],
    thorn[18]: [Region.thorn, max_reachable_vessels, 1],
    thorn[19]: [Region.thorn, max_reachable_vessels, 5],

    cage[1]: [Region.cage, None],
    cage[2]: [Region.cage, None],
    cage[3]: [Region.cage, None],
    cage[4]: [Region.cage, None],
    cage[5]: [Region.cage, None],
    cage[6]: [Region.cage, None],
    cage[7]: [Region.cage, None],
    cage[8]: [Region.cage, None],
    cage[9]: [Region.cage, None],
    cage[10]: [Region.cage, None],
    cage[11]: [Region.cage_not_paranoid, None],
    cage[12]: [Region.cage_not_paranoid, None],
    cage[13]: [Region.cage_not_paranoid, None],
    cage[14]: [Region.cage_not_paranoid, None],
    cage[15]: [Region.cage_not_paranoid, None],
    cage[16]: [Region.cage_paranoid_blade, None],
    cage[17]: [Region.cage_paranoid_blade, None],
    cage[18]: [Region.cage, max_reachable_vessels, 1],
    cage[19]: [Region.cage, max_reachable_vessels, 1],
    cage[20]: [Region.cage, max_reachable_vessels, 5],

    grey[1]: [Region.grey_drowned, None],
    grey[2]: [Region.grey_burned, None],
    grey[3]: [Region.grey_drowned, None],
    grey[4]: [Region.grey_burned, None],
    grey[5]: [Region.grey_drowned, None],
    grey[6]: [Region.grey_burned, None],
    grey[7]: [Region.grey_burned, None],
    grey[8]: [Region.grey_drowned, None],
    grey[9]: [Region.grey_burned, None],
    grey[10]: [Region.grey_drowned, None],
    grey[11]: [Region.grey_burned, None],
    grey[12]: [Region.grey_drowned, None],
    grey[13]: [Region.grey_burned, None],
    grey[14]: [Region.grey_burned, None],
    grey[15]: [Region.grey_burned, max_reachable_vessels, 1],
    grey[16]: [Region.grey_burned, max_reachable_vessels, 1],
    grey[17]: [Region.grey_drowned, max_reachable_vessels, 1],
    grey[18]: [Region.grey_drowned, max_reachable_vessels, 1],
    grey[19]: [Region.grey_burned, max_reachable_vessels, 5],
    grey[20]: [Region.grey_drowned, max_reachable_vessels, 5],

    happily[1]: [Region.happily, None],
    happily[2]: [Region.happily, None],
    happily[3]: [Region.happily_skeptic, None],
    happily[4]: [Region.happily, None],
    happily[5]: [Region.happily_opportunist, None],
    happily[6]: [Region.happily, None],
    happily[7]: [Region.happily, None],
    happily[8]: [Region.happily_blade, None],
    happily[9]: [Region.happily, None],
    happily[10]: [Region.happily, None],
    happily[11]: [Region.happily, None],
    happily[12]: [Region.happily, None],
    happily[13]: [Region.happily, None],
    happily[14]: [Region.happily, None],
    happily[15]: [Region.happily, None],
    happily[16]: [Region.happily, None],
    happily[17]: [Region.happily, max_reachable_vessels, 1],
    happily[18]: [Region.happily, max_reachable_vessels, 1],
    happily[19]: [Region.happily, max_reachable_vessels, 5],
    happily[20]: [Region.happily, max_reachable_vessels, 5],
}
