# Event
credits_reached = "The End of Everything"

filler = "A Filler item"
mirror = "The Mirror"
gift = "A Gift"

# Blade
blade = "Pristine Blade"
blade1 = "Pristine Blade - Chapter 1"
blade2 = "Pristine Blade - Chapter 2"
blade3 = "Pristine Blade - Chapter 3"
blade4 = "Pristine Blade - End"

blade_princess = "Pristine Blade - The Princess"
blade_adversary = "Pristine Blade - The Adversary"
blade_tower = "Pristine Blade - The Tower"
blade_spectre = "Pristine Blade - The Spectre"
blade_nightmare = "Pristine Blade - The Nightmare"
blade_razor = "Pristine Blade - The Razor"
blade_beast = "Pristine Blade - The Beast"
blade_witch = "Pristine Blade - The Witch"
blade_stranger = "Pristine Blade - The Stranger"
blade_prisoner = "Pristine Blade - The Prisoner"
blade_damsel = "Pristine Blade - The Damsel"
blade_needle = "Pristine Blade - The Eye of the Needle"
blade_fury = "Pristine Blade - The Fury"
blade_apotheosis = "Pristine Blade - The Apotheosis"
blade_dragon = "Pristine Blade - The Princess and the Dragon"
blade_clarity = "Pristine Blade - The Moment of Clarity"
blade_den = "Pristine Blade - The Den"
blade_wild = "Pristine Blade - The Wild"
blade_thorn = "Pristine Blade - The Thorn"
blade_cage = "Pristine Blade - The Cage"
blade_grey = "Pristine Blade - The Grey"
blade_happily = "Pristine Blade - The Happily Ever After"
blade_goddess = "Pristine Blade - The End of Everything"

# Princesses
adversary = "The Adversary (Princess)"
tower = "The Tower (Princess)"
spectre = "The Spectre (Princess)"
nightmare = "The Nightmare (Princess)"
razor = "The Razor (Princess)"
beast = "The Beast (Princess)"
witch = "The Witch (Princess)"
stranger = "The Stranger (Princess)"
prisoner = "The Prisoner (Princess)"
damsel = "The Damsel (Princess)"

needle = "The Eye of the Needle (Princess)"
fury = "The Fury (Princess)"
apotheosis = "The Apotheosis (Princess)"
dragon = "The Princess and the Dragon (Princess)"
wraith = "The Wraith (Princess)"
clarity = "The Moment of Clarity (Princess)"
den = "The Den (Princess)"
wild = "The Wild (Princess)"
thorn = "The Thorn (Princess)"
cage = "The Cage (Princess)"
grey = "The Grey (Princess)"
happily = "Happily Ever After (Princess)"

goddess = "The Shifting Mound (Princess)"

# Voices
stubborn = "The Stubborn (Voice)"
broken = "The Broken (Voice)"
cold = "The Cold (Voice)"
paranoid = "The Paranoid (Voice)"
cheated = "The Cheated (Voice)"
hunted = "The Hunted (Voice)"
opportunist = "The Opportunist (Voice)"
contrarian = "The Contrarian (Voice)"
skeptic = "The Skeptic (Voice)"
smitten = "The Smitten (Voice)"
