filler = "A Filler item"
mirror = "The Mirror"
invitation = "An Invitation"
narrator = "The Narrator"
save = "A Save Slot"

# Blade
blade = "Pristine Blade"
blade1 = "Pristine Blade - Chapter 1"
blade2 = "Pristine Blade - Chapter 2"
blade3 = "Pristine Blade - Chapter 3"
blade4 = "Pristine Blade - End"

blade_princess = "Pristine Blade - The Hero and the Princess"
blade_adversary = "Pristine Blade - The Adversary"
blade_tower = "Pristine Blade - The Tower"
blade_spectre = "Pristine Blade - The Spectre"
blade_nightmare = "Pristine Blade - The Nightmare"
blade_razor = "Pristine Blade - The Razor"
blade_beast = "Pristine Blade - The Beast"
blade_witch = "Pristine Blade - The Witch"
blade_stranger = "Pristine Blade - The Stranger"
blade_prisoner = "Pristine Blade - The Prisoner"
blade_damsel = "Pristine Blade - The Damsel"
blade_needle = "Pristine Blade - The Eye of the Needle"
blade_fury = "Pristine Blade - The Fury"
blade_apotheosis = "Pristine Blade - The Apotheosis"
blade_dragon = "Pristine Blade - The Princess and the Dragon"
blade_clarity = "Pristine Blade - The Moment of Clarity"
blade_den = "Pristine Blade - The Den"
blade_wild = "Pristine Blade - The Wild"
blade_thorn = "Pristine Blade - The Thorn"
blade_cage = "Pristine Blade - The Cage"
blade_grey = "Pristine Blade - The Grey"
blade_happily = "Pristine Blade - The Happily Ever After"
blade_goddess = "Pristine Blade - The End of Everything"

sword = "Pristine Sword"

# Princesses
adversary = "Princess - The Adversary"
tower = "Princess - The Tower"
spectre = "Princess - The Spectre"
nightmare = "Princess - The Nightmare"
razor = "Princess - The Razor"
beast = "Princess - The Beast"
witch = "Princess - The Witch"
stranger = "Princess - The Stranger"
prisoner = "Princess - The Prisoner"
damsel = "Princess - The Damsel"

needle = "Princess - The Eye of the Needle"
fury = "Princess - The Fury"
apotheosis = "Princess - The Apotheosis"
dragon = "Princess - The Princess and the Dragon"
wraith = "Princess - The Wraith"
clarity = "Princess - The Moment of Clarity"
den = "Princess - The Den"
wild = "Princess - The Wild"
thorn = "Princess - The Thorn"
cage = "Princess - The Cage"
grey = "Princess - The Grey"
happily = "Princess - Happily Ever After"

goddess = "Princess - The Shifting Mound"

# Voices
stubborn = "Voice - The Stubborn"
broken = "Voice - The Broken"
cold = "Voice - The Cold"
paranoid = "Voice - The Paranoid"
cheated = "Voice - The Cheated"
hunted = "Voice - The Hunted"
opportunist = "Voice - The Opportunist"
contrarian = "Voice - The Contrarian"
skeptic = "Voice - The Skeptic"
smitten = "Voice - The Smitten"
