# Chapter
chap2 = "Reach Chapter 2"
chap3 = "Reach Chapter 3"

# Oblivion
oblivion1 = "Denial"
oblivion2 = "Anger"
oblivion3 = "Bargaining"
oblivion4 = "Depression"
oblivion5 = "Acceptance"
oblivion6 = "Oblivion"

# The Mirror
mirror1 = "The Body"
mirror2 = "The Bloat"
mirror3 = "The Decay"
mirror4 = "The Remains"
mirror5 = "The Long Quiet"

mirror_adversary = "Mirror in The Adversary"
mirror_tower = "Mirror in The Tower"
mirror_spectre = "Mirror in The Spectre"
mirror_nightmare = "Mirror in The Nightmare"
mirror_razor = "Mirror in The Razor"
mirror_beast = "Mirror in The Beast"
mirror_witch = "Mirror in The Witch"
mirror_stranger = "Mirror in The Stranger"
mirror_prisoner = "Mirror in The Prisoner"
mirror_damsel = "Mirror in The Damsel"

mirror_needle = "Mirror in The Eye of the Needle"
mirror_fury = "Mirror in The Fury"
mirror_wraith = "Mirror in The Wraith"
mirror_clarity = "Mirror in The Moment of Clarity"
mirror_den = "Mirror in The Den"
mirror_thorn = "Mirror in The Thorn"
mirror_cage = "Mirror in The Cage"
mirror_grey = "Mirror in The Grey"
mirror_happily = "Mirror in Happily Ever After"

# Gifts
gift1 = "Bring 1 Gift"
gift2 = "Bring 2 Gifts"
gift3 = "Bring 3 Gifts"
gift4 = "Bring 4 Gifts"
gift5 = "Bring 5 Gifts"

# Princesses
adversary = "Find The Adversary"
tower = "Find The Tower"
spectre = "Find The Spectre"
nightmare = "Find The Nightmare"
razor = "Find The Razor"
beast = "Find The Beast"
witch = "Find The Witch"
stranger = "Find The Stranger"
prisoner = "Find The Prisoner"
damsel = "Find The Damsel"

needle = "Find The Eye of the Needle"
fury = "Find The Fury"
apotheosis = "Find The Apotheosis"
dragon = "Find The Princess and the Dragon"
wraith = "Find The Wraith"
clarity = "Find The Moment of Clarity"
den = "Find The Den"
wild = "Find The Wild"
thorn = "Find The Thorn"
cage = "Find The Cage"
grey = "Find The Grey"
happily = "Find Happily Ever After"

goddess = "Find The Shifting Mound"

# Heart
adversary_heart = "A Bold Heart"
tower_heart = "An Overwhelming Heart"
spectre_heart = "A Yearning Heart"
nightmare_heart = "A Tender Heart"
razor_heart = "A Piercing Heart [in a Cage of Iron or Beating Free]"
razor_heart_iron = "A Piercing Heart in a Cage of Iron"
razor_heart_free = "A Piercing Heart, Beating Free"
beast_heart = "A Cunning Heart"
witch_heart = "A Righteous Heart"
stranger_heart = "A Rich and Vibrant Heart"
prisoner_heart = "A [Patient or Clever] Heart"
prisoner_heart_patient = "A Patient Heart"
prisoner_heart_clever = "A Clever Heart"
damsel_heart = "A [Gentle or Pliable] Heart"
damsel_heart_gentle = "A Gentle Heart"
damsel_heart_pliable = "A Pliable Heart"

needle_heart = "A Burning Heart"
fury_heart = "A Weathered Heart [Held in Ribbons]"
fury_heart_weathered = "A Weathered Heart"
fury_heart_unwound = "A Weathered Heart, Held in Ribbons"
apotheosis_heart = "A Terrifying and Divine Heart"
dragon_heart = "An Empathetic Heart [Held in Stencil]"
dragon_heart_main = "An Empathetic Heart"
dragon_heart_stencil = "An Empathetic Heart, Held in Stencil"
wraith_heart = "A Driven Heart"
clarity_heart = "A Wise Heart"
den_heart = "A Ravenous Heart"
wild_heart = "A [Curious or Scarred] and Beautiful Heart"
wild_heart_curious = "A Curious and Beautiful Heart"
wild_heart_scarred = "A Scarred and Beautiful Heart"
thorn_heart = "A Cautious Heart"
cage_heart = "An Open Heart, or a Watchful One"
grey_heart = "A [Bright or Deep] Heart"
grey_heart_bright = "A Bright Heart"
grey_heart_deep = "A Deep Heart"
happily_heart = "An Honest Heart"
