one = "Chapter I - The Hero and the Princess"
one_blade = "Chapter I - The Hero and the Princess [Blade Only]"
chap2 = "Chapter II"
chap3 = "Chapter III"

adversary = "Chapter II - The Adversary"
tower = "Chapter II - The Tower"
spectre = "Chapter II - The Spectre"
nightmare = "Chapter II - The Nightmare"
razor = "Chapter II - The Razor"
beast = "Chapter II - The Beast"
witch = "Chapter II - The Witch"
stranger = "Chapter II - The Stranger"
prisoner = "Chapter II - The Prisoner"
damsel = "Chapter II - The Damsel"

adversary_blade = "Chapter II - The Adversary [Blade Only]"
tower_blade = "Chapter II - The Tower [Blade Only]"
spectre_blade = "Chapter II - The Spectre [Blade Only]"
nightmare_blade = "Chapter II - The Nightmare [Blade Only]"
razor_blade = "Chapter II - The Razor [Blade Only]"
beast_blade = "Chapter II - The Beast [Blade Only]"
witch_blade = "Chapter II - The Witch [Blade Only]"
stranger_blade = "Chapter II - The Stranger [Blade Only]"
prisoner_blade = "Chapter II - The Prisoner [Blade Only]"
damsel_blade = "Chapter II - The Damsel [Blade Only]"

needle = "Chapter III - The Eye of the Needle"
needle_blade = "Chapter III - The Eye of the Needle [Blade Only]"
needle_hunted = "Chapter III - The Eye of the Needle (Hunted)"
needle_hunted_blade = "Chapter III - The Eye of the Needle (Hunted) [Blade Only]"
needle_skeptic = "Chapter III - The Eye of the Needle (Skeptic)"

fury = "Chapter III - The Fury"
fury_weathered_heart = "Chapter III - The Fury (Weathered Heart)"
fury_unwound_heart = "Chapter III - The Fury (Unwound Heart)"
fury_cold = "Chapter III - The Fury (Cold)"
fury_contrarian = "Chapter III - The Fury (Contrarian)"
fury_broken = "Chapter III - The Fury (Broken)"
fury_tower = "Chapter III - The Fury (Tower)"
fury_tower_blade = "Chapter III - The Fury (Tower) [Blade Only]"
fury_broken_cold = "Chapter III - The Fury (Broken & Cold)"
fury_broken_cold_blade = "Chapter III - The Fury (Broken & Cold) [Blade Only]"

apotheosis = "Chapter III - The Apotheosis"
apotheosis_blade = "Chapter III - The Apotheosis [Blade Only]"
apotheosis_contrarian = "Chapter III - The Apotheosis (Contrarian)"
apotheosis_contrarian_blade = "Chapter III - The Apotheosis (Contrarian) [Blade Only]"
apotheosis_paranoid = "Chapter III - The Apotheosis (Paranoid)"
apotheosis_paranoid_blade = "Chapter III - The Apotheosis (Paranoid) [Blade Only]"
apotheosis_paranoid_sword = "Chapter III - The Apotheosis (Paranoid) [Sword Only]"

dragon = "Chapter III - The Princess and the Dragon"
dragon_fuse = "Chapter III - The Princess and the Dragon (Fuse)"
dragon_kind = "Chapter III - The Princess and the Dragon (Kind Princess)"
dragon_kind_blade = "Chapter III - The Princess and the Dragon (Kind Princess) [Blade Only]"
dragon_harsh = "Chapter III - The Princess and the Dragon (Harsh Princess)"

wraith = "Chapter III - The Wraith"
wraith_cheated = "Chapter III - The Wraith (Cheated)"
wraith_paranoid = "Chapter III - The Wraith (Paranoid)"
wraith_cold = "Chapter III - The Wraith (Cold)"
wraith_opportunist = "Chapter III - The Wraith (Opportunist)"

clarity = "Chapter ??? - The Moment of Clarity"
clarity_blade = "Chapter ??? - The Moment of Clarity [Blade Only]"

razor_chap3 = "Chapter III - The Razor"
razor_no_way = "Chapter III - No Way Out"
razor_no_way_broken = "Chapter III - No Way Out (Broken)"
razor_no_way_paranoid = "Chapter III - No Way Out (Paranoid)"

razor_race = "Chapter III - The Arms Race"
razor_race_broken = "Chapter III - The Arms Race (Broken)"
razor_race_paranoid = "Chapter III - The Arms Race (Paranoid)"
razor_race_stubborn = "Chapter III - The Arms Race (Stubborn)"

den = "Chapter III - The Den"
den_blade = "Chapter III - The Den [Blade Only]"
den_skeptic = "Chapter III - The Den (Skeptic)"
den_skeptic_blade = "Chapter III - The Den (Skeptic) [Blade Only]"
den_stubborn = "Chapter III - The Den (Stubborn)"
den_stubborn_blade = "Chapter III - The Den (Stubborn) [Blade Only]"

wild = "Chapter III - The Wild"
wild_blade = "Chapter III - The Wild [Blade Only]"
wild_beast_broken = "Chapter III - The Wild (Broken)"
wild_beast_contrarian = "Chapter III - The Wild (Contrarian)"
wild_beast_opportunist = "Chapter III - The Wild (Opportunist)"
wild_beast_stubborn = "Chapter III - The Wild (Beast - Stubborn)"
wild_witch_stubborn = "Chapter III - The Wild (Witch - Stubborn)"
wild_witch_cheated = "Chapter III - The Wild (Cheated)"
wild_witch_paranoid = "Chapter III - The Wild (Paranoid)"

thorn = "Chapter III - The Thorn"
thorn_blade = "Chapter III - The Thorn [Blade Only]"
thorn_smitten = "Chapter III - The Thorn (Smitten)"
thorn_smitten_blade = "Chapter III - The Thorn (Smitten) [Blade Only]"
thorn_cheated = "Chapter III - The Thorn (Cheated)"

cage = "Chapter III - The Cage"
cage_paranoid = "Chapter III - The Cage (Paranoid)"
cage_paranoid_blade = "Chapter III - The Cage (Paranoid) [Blade Only]"
cage_cheated = "Chapter III - The Cage (Cheated)"
cage_broken = "Chapter III - The Cage (Broken)"
cage_not_paranoid = "Chapter III - The Cage (Not Paranoid)"
cage_new_world = "Chapter III - The Cage (New World)"

grey = "Chapter III - The Grey"
grey_drowned = "Chapter III - The Grey (Drowned)"
grey_burned = "Chapter III - The Grey (Burned)"

happily = "Epilogue - Happily Ever After"
happily_blade = "Epilogue - Happily Ever After [Blade Only]"
happily_skeptic = "Epilogue - Happily Ever After (Skeptic)"
happily_opportunist = "Epilogue - Happily Ever After (Opportunist)"

razor_chap4 = "Chapter IV - The Razor"
razor_empty = "Chapter IV - The Empty Cup"
razor_destruction = "Chapter IV - Mutually Assured Destruction"

space_between = "The Space Between"
oblivion = "The Oblivion"
restart = "Loop Restart"
goddess = "The End of Everything"
goddess_blade = "The End of Everything [Blade Only]"
stranger_goddess = "The Stranger - The End of Everything"
stranger_goddess_blade = "The Stranger - The End of Everything [Blade Only]"
new_world = "Your New World"